app = 'microbiology-krok-bot'
primary_region = 'ams'

[build]

[env]
  TZ = 'Europe/Kyiv'

[[mounts]]
  source = 'bot_data'
  destination = '/data'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
